version: "3.8"

services:
  fastapi-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    container_name: fastapi-review-analyzer

  frontend:
    image: nginx:alpine
    container_name: static-frontend
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "5500:80"
